name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main  # 监听 main 分支的变化，触发构建

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 如果有需要的依赖，可以加上

      - name: Build the docs
        run: |
          sphinx-build -b html docs/source docs/_build/html

      - name: Create .nojekyll file
        run: |
          touch docs/_build/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs/_build/html
          publish_branch: gh-pages  # 将构建结果发布到 gh-pages 分支
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'
